projects/web/__init__.py
from projects.web.routes import perpus

projects/web/routes.py
import json
import gc
import calendar

from builtins import print

from flask import Blueprint, render_template, session, redirect, request, jsonify, url_for
from projects.login_required import login_required

perpus = Blueprint('perpus', __name__, template_folder='templates', static_folder='static', url_prefix='/')


@perpus.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return 'Welcome to web perpustakaan'


@perpus.route('/signin', methods=['GET', 'POST'])
def sign_in():
    try:

        if request.method == "POST":
            usr = request.form['username']
            pwd = request.form['password']

        return render_template('authorize/signin.html')
    except Exception as e:
        return render_template('authorize/signin.html')

projects/web/templates/authorize/signin.html
{% extends 'base_login.html' %}

{% block content %}
    <div class="login-box animation__shake">
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="{{ url_for('perpus.index') }}" class="h1">PERPUSTAKAAN</a>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form role="form" method="post" action="{{ url_for('perpus.sign_in') }}">
                    <div class="input-group mb-3">
                        <input type="username" id="username" name="username"
                               class="form-control" placeholder="Username"
                               value="{{ request.form.username }}">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-user-tie"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" id="password" name="password"
                               class="form-control" placeholder="Password"
                               value="{{ request.form.password }}">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-8"></div>
                        <div class="col-4">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

projects/web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>PERPUSTAKAAN</title>

    {% block head_collect %}{% include 'head_collect.html' %}{% endblock %}

</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed pray-body">

<div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__wobble" src="../static/assets/dist/img/AdminLTELogo.png" alt="PERPUS" height="60" width="60">
    </div>

    {% block content %}{% endblock %}

</div>

    {% block foot_collect %}{% include 'foot_collect.html' %}{% endblock %}

</body>
</html>

projects/web/templates/base_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>PERPUSTAKAAN</title>

    {% block head_collect %}{% include 'head_collect.html' %}{% endblock %}

</head>
<body class="hold-transition dark-mode login-page">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__wobble" src="../static/assets/dist/img/AdminLTELogo.png" alt="PERPUS" height="60" width="60">
    </div>

    {% block content %}{% endblock %}

    {% block foot_collect %}{% include 'foot_collect.html' %}{% endblock %}

</body>
</html>

projects/web/templates/foot_collect.html
{% block foot_collect %}

    <!-- Bootstrap 4 -->
    <script src="../static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../static/assets/dist/js/adminlte.min.js"></script>

{% endblock %}

projects/web/templates/head_collect.html
{% block head_collect %}

    <!-- Font Awesome -->
    <link rel="stylesheet" href="../static/assets/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../static/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../static/assets/dist/css/adminlte.min.css">
    <!-- Custome style -->
    <link rel="stylesheet" href="../static/assets/dist/css/abdullah.css">

    <!-- jQuery -->
    <script src="../static/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Custome js -->
    <script src="../static/assets/dist/js/abdullah.js"></script>

{% endblock %}